version: '3.4'

services:
  #personalfinancemanagement:
  #  image: ${DOCKER_REGISTRY-}personalfinancemanagement
  #  build:
  #    context: .
  #    dockerfile: PersonalFinanceManagement/Dockerfile
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret1234
    volumes:
        - ~/apps/mssql/data:/var/lib/mssqlql/data