/**
 * Personal Finance Management API
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Debit (`d`) for liabilities or credit (`c`) for assets
 */
export type DirectionsEnum = 'd' | 'c';

export const DirectionsEnum = {
    D: 'd' as DirectionsEnum,
    C: 'c' as DirectionsEnum
};