/**
 * Personal Finance Management API
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SpendingInCategory } from './spendingInCategory';

/**
 *  
 */
export interface SpendingsByCategory { 
    /**
     * List of spendings by category
     */
    groups?: Array<SpendingInCategory>;
}