/**
 * Personal Finance Management API
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *  
 */
export interface SpendingInCategory { 
    /**
     * Code of the category
     */
    catcode?: string;
    /**
     * Amount spent in category
     */
    amount?: number;
    /**
     * Number of transactions included in group
     */
    count?: number;
}