/**
 * Personal Finance Management API
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PagedList } from './pagedList';
import { SortOrderEnum } from './sortOrderEnum';
import { TransactionWithSplits } from './transactionWithSplits';

/**
 *  
 */
export interface TransactionPagedList extends PagedList { 
    items?: Array<TransactionWithSplits>;
}