/**
 * Personal Finance Management API
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DirectionsEnum } from './directionsEnum';
import { MccCodeEnum } from './mccCodeEnum';
import { SingleCategorySplit } from './singleCategorySplit';
import { Transaction } from './transaction';
import { TransactionKindsEnum } from './transactionKindsEnum';

/**
 * transaction-with-splits
 */
export interface TransactionWithSplits extends Transaction { 
    splits?: Array<SingleCategorySplit>;
}