/**
 * Personal Finance Management API
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Enumeration that distinguishes between accounting transactions based on their effect on the customer accounts.
 */
export type TransactionKindsEnum = 'dep' | 'wdw' | 'pmt' | 'fee' | 'inc' | 'rev' | 'adj' | 'lnd' | 'lnr' | 'fcx' | 'aop' | 'acl' | 'spl' | 'sal';

export const TransactionKindsEnum = {
    Dep: 'dep' as TransactionKindsEnum,
    Wdw: 'wdw' as TransactionKindsEnum,
    Pmt: 'pmt' as TransactionKindsEnum,
    Fee: 'fee' as TransactionKindsEnum,
    Inc: 'inc' as TransactionKindsEnum,
    Rev: 'rev' as TransactionKindsEnum,
    Adj: 'adj' as TransactionKindsEnum,
    Lnd: 'lnd' as TransactionKindsEnum,
    Lnr: 'lnr' as TransactionKindsEnum,
    Fcx: 'fcx' as TransactionKindsEnum,
    Aop: 'aop' as TransactionKindsEnum,
    Acl: 'acl' as TransactionKindsEnum,
    Spl: 'spl' as TransactionKindsEnum,
    Sal: 'sal' as TransactionKindsEnum
};