/**
 * Personal Finance Management API
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { DirectionsEnum } from './directionsEnum';
import { MccCodeEnum } from './mccCodeEnum';
import { TransactionKindsEnum } from './transactionKindsEnum';

/**
 * transaction
 */
export interface Transaction {
    /**
     * Id of the transaction
     */
    readonly id: number;
    /**
     * beneficiary name
     */
    beneficiaryName?: string;
    /**
     * Date of the transaction
     */
    date: string;
    direction: DirectionsEnum;
    /**
     * Transaction amount
     */
    amount: number;
    /**
     * Transaction description
     */
    description?: string;
    /**
     * Currency for transaction. ISO 4217 currency code.
     */
    currency: string;
    mcc?: MccCodeEnum;
    kind: TransactionKindsEnum;
    /**
     * Code of category. If literal it's category, If number it is a sub category code.
     */
    readonly categoryDto?: Category;
}
